[build]
command = "react-router build"
publish = "build/client"

[dev]
command = "react-router dev"

[[redirects]]
  from = "/episodes"
  to = "https://rss.castbox.fm/everest/cc803d4a973f4758b2eafb046573d642.xml"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
