[build]
command = "react-router build"
publish = "build/client"
functions = "netlify/functions"

[build.environment]
VITE_RSS_URL = "http://rss.castbox.fm/everest/cc803d4a973f4758b2eafb046573d642.xml"

[dev]
command = "react-router dev"

[[redirects]]
from = "/functions/*"
to = "/functions/:splat"
status = 200
force = true
