[build]
command = "react-router build"
publish = "build/client"
functions = "netlify/functions"

[dev]
command = "react-router dev"

[[redirects]]
from = "/functions/*"
to = "/functions/:splat"
status = 200
force = true
