[build]
command = "react-router build"
publish = "build/client"
functions = "netlify/functions"

[functions]
node_bundler = "nft"
included_files = ["build/server/**"]

[functions.fetch-openai]
memory_size = 1024
timeout = 30

[functions.contact-simple]
timeout = 10

[build.environment]
VITE_RSS_URL = "http://rss.castbox.fm/everest/cc803d4a973f4758b2eafb046573d642.xml"

[dev]
command = "react-router dev"
functions = "netlify/functions"
publish = "build/client"
port = 8888

# For local production testing, manually override with:
# npx netlify dev --dir build/client --port 8888

[[redirects]]
from = "/functions/*"
to = "/functions/:splat"
status = 200
force = true

# Assets should be served statically - MUST come before catch-all
[[redirects]]
from = "/assets/*"
to = "/assets/:splat"
status = 200
force = true

# Serve the static contact.html file for Netlify Forms processing only
[[redirects]]
from = "/contact.html"
to = "/contact.html"
status = 200
force = true

# Force /contact route to React Router (prevent static contact.html from being served)
[[redirects]]
from = "/contact"
to = "/functions/react-router-server"
status = 200
force = true

# Handle React Router SSR - send all other routes to the server (MUST be last)
[[redirects]]
from = "/*"
to = "/functions/react-router-server"
status = 200
conditions = {Path = "!/assets/*"}
force = false
