[build]
command = "react-router build"
publish = "build/client"
functions = "netlify/functions"

[dev]
command = "react-router dev"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
